language: android
android:
    components:
        - build-tools-27.0.3
        - android-27
before_script:
  - echo yes | sdkmanager "platforms;android-27" &>/dev/null
  - echo yes | sdkmanager "system-images;android-27;default;armeabi-v7a" &>/dev/null
script: 
- ./gradlew build connectedCheck
- ./gradlew test