language: android
android:
    components:
        - build-tools-27.0.3
        - android-27
before_script:
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-27,sys-img-x86_64-android-27
- android list targets
- echo no | android create avd --force -n test -t android-27 --abi arm64-v8a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- abd shell input keyevent 82 &
script: 
- ./gradlew build connectedCheck
- ./gradlew test